# Generated by Django 3.1.12 on 2025-07-16 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_processor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobposting',
            name='job_analysis',
        ),
        migrations.RemoveField(
            model_name='jobposting',
            name='nice_to_have',
        ),
        migrations.RemoveField(
            model_name='jobposting',
            name='requirements',
        ),
        migrations.RemoveField(
            model_name='rankingsession',
            name='ranking_results',
        ),
        migrations.RemoveField(
            model_name='rankingsession',
            name='summary',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='parsed_data',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='processed_data',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='ranking_data',
        ),
        migrations.AddField(
            model_name='jobposting',
            name='job_analysis_json',
            field=models.TextField(default='{}'),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='nice_to_have_json',
            field=models.TextField(default='[]'),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='requirements_json',
            field=models.TextField(default='[]'),
        ),
        migrations.AddField(
            model_name='rankingsession',
            name='ranking_results_json',
            field=models.TextField(default='[]'),
        ),
        migrations.AddField(
            model_name='rankingsession',
            name='summary_json',
            field=models.TextField(default='{}'),
        ),
        migrations.AddField(
            model_name='resume',
            name='parsed_data_json',
            field=models.TextField(default='{}'),
        ),
        migrations.AddField(
            model_name='resume',
            name='processed_data_json',
            field=models.TextField(default='{}'),
        ),
        migrations.AddField(
            model_name='resume',
            name='ranking_data_json',
            field=models.TextField(default='{}'),
        ),
    ]
