# Generated by Django 3.1.12 on 2025-07-16 07:47

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(default='legacy', max_length=255, unique=True)),
                ('title', models.CharField(default='unknown', max_length=255)),
                ('company', models.CharField(default='unknown', max_length=255)),
                ('description', models.TextField(default='')),
                ('requirements', djongo.models.fields.JSONField(default=list)),
                ('nice_to_have', djongo.models.fields.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='active', max_length=20)),
                ('job_analysis', djongo.models.fields.JSONField(default=dict)),
            ],
            options={
                'db_table': 'job_postings',
            },
        ),
        migrations.CreateModel(
            name='RankingSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(default='legacy', max_length=255, unique=True)),
                ('job_id', models.CharField(default='legacy', max_length=255)),
                ('job_description', models.TextField(default='')),
                ('candidates_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='processing', max_length=20)),
                ('ranking_results', djongo.models.fields.JSONField(default=list)),
                ('summary', djongo.models.fields.JSONField(default=dict)),
            ],
            options={
                'db_table': 'ranking_sessions',
            },
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_id', models.CharField(default='legacy', max_length=255, unique=True)),
                ('filename', models.CharField(default='unknown', max_length=255)),
                ('original_file_path', models.CharField(default='unknown', max_length=500)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('processing_status', models.CharField(default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('parsed_data', djongo.models.fields.JSONField(default=dict)),
                ('processed_data', djongo.models.fields.JSONField(default=dict)),
                ('ranking_data', djongo.models.fields.JSONField(default=dict)),
            ],
            options={
                'db_table': 'resumes',
            },
        ),
    ]
