# Generated by Django 3.1.12 on 2025-07-22 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_processor', '0002_auto_20250716_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='candidate_id',
            field=models.CharField(default='legacy', max_length=255),
        ),
    ]
